apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp

spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
      name: myapp-pod
      labels:
        env: production
    spec:
      containers:
        - name: myapp
          image: nginx